# Generated by Django 4.0.2 on 2024-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Есть в наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='returnable',
            field=models.BooleanField(default=True, verbose_name='Возможен возврат'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Принят', 'Принят'), ('Собран', 'Собран'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='В ожижании', max_length=50),
        ),
    ]
