# Generated by Django 4.0.2 on 2024-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_discount_product_in_stock_product_returnable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_offer',
            field=models.BooleanField(default=False, verbose_name='Лучшее предложение'),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_now',
            field=models.BooleanField(default=False, verbose_name='Купить сейчас'),
        ),
    ]
