# Generated by Django 4.0.2 on 2024-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_best_offer_alter_product_buy_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_offer',
            field=models.BooleanField(default=False, verbose_name='Лучшее предложение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_now',
            field=models.BooleanField(default=False, verbose_name='Купить сейчас'),
        ),
    ]
